name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Клон репо
      - uses: actions/checkout@v3

      # Встановити Python 3.13
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      # Встановити pip (якщо треба)
      - run: python -m pip install --upgrade pip

      # Встановити залежності, якщо файл є
      - run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - run: pytest $(find . -type d -name tests)
      - run: pytest lesson_3/tests/
